image: ubuntu

version: '0.{build}'

install:
  - sh: sudo apt-get update; sudo apt-get install -y gcc-mingw-w64

test: off

build_script:
  - sh: make clean zip

artifacts:
  - path: ntfszapfree.zip

skip_tags: true
